// Table Infomaion

// Common
const VAR_DYNAMODB_KEY_TYPE_STRING = "S";
const VAR_DYNAMODB_KEY_TYPE_NUMBER = "N";
const VAR_DYNAMODB_KEY_TYPE_BINARY = "BOOL";

// Table Configration
const VAR_DYNAMODB_HASH_KEY_TYPE = "HASH";
const VAR_DYNAMODB_SORT_KEY_TYPE = "RANGE";

// User Table
const VAR_DYNAMODB_USER_TABLE_NAME = "User";
const VAR_DYNAMODB_USER_TABLE_PK = "uid";
const VAR_DYNAMODB_USER_TABLE_ITEM_UID = "uid";
const VAR_DYNAMODB_USER_TABLE_ITEM_EMAIL = "email";
const VAR_DYNAMODB_USER_TABLE_ITEM_NAME = "name";

// Dog Table
const VAR_DYNAMODB_DOG_TABLE_NAME = "Dog";
const VAR_DYNAMODB_DOG_TABLE_PK = "id";
const VAR_DYNAMODB_DOG_TABLE_ITEM_ID = "id";
const VAR_DYNAMODB_DOG_TABLE_ITEM_NAME = "name";
const VAR_DYNAMODB_DOG_TABLE_ITEM_HOST_ID = "hostId";
const VAR_DYNAMODB_DOG_TABLE_GSI_NAME = "hostIdIndex";

// Test Configration
const VAR_TEST_DYNAMODB_BILLING_MODE = "PAY_PER_REQUEST"; // PAY_PER_REQUEST | PROVISIONED
const VAR_TEST_DYNAMODB_AWS_REGION = "us-west-2";
const VAR_TEST_DYNAMODB_AWS_ACCESS_KEY = "dummyAccessKeyId";
const VAR_TEST_DYNAMODB_AWS_SECRET_ACCESS_KEY = "dummySecretAccessKey";
