const VAR_API_MIDDLEWARE_AUTHORIZATION_HEADER = "Authorization";
const VAR_API_MIDDLEWARE_AUTHORIZATION_HEADED_PREFIX = "Bearer ";

// API ERROR MESSAGES
const VAR_API_MIDDLEWARE_401_ERROR_MESSAGE = "Authorization header is invalid";
