services:
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -port 8000
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal

  api:
    build: .
    environment:
      - ON_DEVELOPMENT=true
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - TABLE_PREFIX=Test_
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    volumes:
      - ./src:/home/app/src
      - ./package.json:/home/app/package.json
      - ./tsconfig.json:/home/app/tsconfig.json
    working_dir: /home/app
    command: npm test
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
