services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    hostname: dynamodb-local
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -port 8000"
    ports:
      - "8000:8000"

  api:
    build: .
    environment:
      - ON_DEVELOPMENT=true
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - TABLE_PREFIX=Test_
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}

    command: node --test
    depends_on:
      - dynamodb-local
