name: Docker Image CI

on:
  pull_request:
    branches: ["develop", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    env:
      DYNAMODB_ENDPOINT: http://localhost:8000
      TABLE_PREFIX: Test_
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test Script
        run: |
          chmod +x test.sh
          ./test.sh
