name: Docker Image CI

on:
  pull_request:
    branches: ["develop", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TABLE_PREFIX: ${{ secrets.TABLE_PREFIX }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --tag node_image:latest

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 \
            -e PORT=3000 \
            -e AWS_REGION=${AWS_REGION} \
            -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            -e TABLE_PREFIX=${TABLE_PREFIX} \
            node_image:latest

      - if: github.base_ref == 'develop'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: github.base_ref == 'develop'
        run: npm install

      - name: Run tests
        if: github.base_ref == 'develop'
        run: npm test
